"""
Universe-to-universe translator for Project ℵω.

This module translates statements from one toy formal universe into another.
It tracks preserved symbols, lost symbols, added symbols, preserved features,
lost features, truth-value changes, proof-status changes, and meaning changes.

This is a heuristic bridge engine, not a formal equivalence checker.
"""

from dataclasses import replace
from typing import List, Tuple

from src.bridges.bridge_map import BridgeMap
from src.bridges.translation_result import (
    MeaningChange,
    MeaningChangeKind,
    TranslationResult,
    TranslationStatus,
)
from src.toy_topoi.internal_language import InternalLanguageAnalyzer
from src.toy_topoi.statements import Statement
from src.toy_topoi.universe import FormalUniverse


class UniverseTranslator:
    """
    Translates statements between toy formal universes.
    """

    def __init__(self) -> None:
        self.analyzer = InternalLanguageAnalyzer()

    def translate(
        self,
        statement: Statement,
        source_universe: FormalUniverse,
        target_universe: FormalUniverse,
        bridge: BridgeMap,
    ) -> TranslationResult:
        """
        Translates one statement from a source universe into a target universe.
        """

        source_analysis = self.analyzer.analyze(statement, source_universe)

        translated_symbols, preserved_symbols, lost_symbols, added_symbols = self._translate_symbols(
            statement=statement,
            bridge=bridge,
        )

        translated_statement = self._build_translated_statement(
            statement=statement,
            target_universe=target_universe,
            translated_symbols=translated_symbols,
            bridge=bridge,
        )

        target_analysis = self.analyzer.analyze(translated_statement, target_universe)

        source_truth_value = source_analysis.recommended_truth_value
        target_truth_value = bridge.map_truth_value(target_analysis.recommended_truth_value)

        source_proof_status = source_analysis.recommended_proof_status
        target_proof_status = bridge.map_proof_status(target_analysis.recommended_proof_status)

        preserved_features, lost_features = self._translate_features(
            source_features=source_analysis.required_features,
            bridge=bridge,
        )

        meaning_changes = self._meaning_changes(
            source_truth_value=source_truth_value,
            target_truth_value=target_truth_value,
            source_proof_status=source_proof_status,
            target_proof_status=target_proof_status,
            lost_symbols=lost_symbols,
            lost_features=lost_features,
            source_analysis=source_analysis,
            target_analysis=target_analysis,
            bridge=bridge,
        )

        status = self._translation_status(
            lost_symbols=lost_symbols,
            lost_features=lost_features,
            meaning_changes=meaning_changes,
            source_fit=source_analysis.universe_fit_score,
            target_fit=target_analysis.universe_fit_score,
        )

        confidence = self._translation_confidence(
            bridge=bridge,
            lost_symbols=lost_symbols,
            lost_features=lost_features,
            meaning_changes=meaning_changes,
            target_fit=target_analysis.universe_fit_score,
            target_ambiguity=target_analysis.ambiguity_score,
        )

        return TranslationResult(
            source_statement=statement,
            translated_statement=translated_statement,
            source_universe_name=source_universe.name,
            target_universe_name=target_universe.name,
            source_truth_value=source_truth_value,
            target_truth_value=target_truth_value,
            source_proof_status=source_proof_status,
            target_proof_status=target_proof_status,
            preserved_symbols=preserved_symbols,
            lost_symbols=lost_symbols,
            added_symbols=added_symbols,
            preserved_features=preserved_features,
            lost_features=lost_features,
            meaning_changes=meaning_changes,
            translation_status=status,
            translation_confidence=confidence,
            notes=(
                "Generated by the heuristic UniverseTranslator. "
                "This translation is a computational diagnostic, not a formal proof."
            ),
            metadata={
                "source_fit_score": str(source_analysis.universe_fit_score),
                "target_fit_score": str(target_analysis.universe_fit_score),
                "source_ambiguity_score": str(source_analysis.ambiguity_score),
                "target_ambiguity_score": str(target_analysis.ambiguity_score),
                "bridge_strength_score": str(bridge.bridge_strength_score()),
            },
        )

    @staticmethod
    def _translate_symbols(
        statement: Statement,
        bridge: BridgeMap,
    ) -> Tuple[List[str], List[str], List[str], List[str]]:
        """
        Translates required symbols through a bridge.
        """

        translated_symbols: List[str] = []
        preserved_symbols: List[str] = []
        lost_symbols: List[str] = []
        added_symbols: List[str] = []

        for symbol in statement.required_symbols:
            mapped = bridge.map_symbol(symbol)

            if mapped is None:
                lost_symbols.append(symbol)
                continue

            translated_symbols.append(mapped)

            if mapped == symbol:
                preserved_symbols.append(symbol)
            else:
                preserved_symbols.append(symbol)
                added_symbols.append(mapped)

        return (
            sorted(set(translated_symbols)),
            sorted(set(preserved_symbols)),
            sorted(set(lost_symbols)),
            sorted(set(added_symbols)),
        )

    @staticmethod
    def _build_translated_statement(
        statement: Statement,
        target_universe: FormalUniverse,
        translated_symbols: List[str],
        bridge: BridgeMap,
    ) -> Statement:
        """
        Creates the translated statement object.
        """

        symbolic_form = statement.symbolic_form

        for mapping in bridge.symbol_mappings:
            if mapping.target_symbol is None:
                symbolic_form = symbolic_form.replace(mapping.source_symbol, f"[LOST:{mapping.source_symbol}]")
            else:
                symbolic_form = symbolic_form.replace(mapping.source_symbol, mapping.target_symbol)

        translated_notes = (
            f"Translated from '{statement.origin_universe or bridge.source_universe_name}' "
            f"into '{target_universe.name}' using bridge '{bridge.name}'. "
            f"Original notes: {statement.notes}"
        )

        return replace(
            statement,
            name=f"Translated {statement.name}",
            symbolic_form=symbolic_form,
            required_symbols=translated_symbols,
            origin_universe=target_universe.name,
            notes=translated_notes,
        )

    @staticmethod
    def _translate_features(
        source_features: List[str],
        bridge: BridgeMap,
    ) -> Tuple[List[str], List[str]]:
        """
        Translates required features through a bridge.
        """

        preserved_features: List[str] = []
        lost_features: List[str] = []

        for feature in source_features:
            mapped = bridge.map_feature(feature)

            if mapped is None:
                lost_features.append(feature)
            else:
                preserved_features.append(feature)

        return sorted(set(preserved_features)), sorted(set(lost_features))

    @staticmethod
    def _meaning_changes(
        source_truth_value,
        target_truth_value,
        source_proof_status,
        target_proof_status,
        lost_symbols: List[str],
        lost_features: List[str],
        source_analysis,
        target_analysis,
        bridge: BridgeMap,
    ) -> List[MeaningChange]:
        """
        Builds meaning-change records.
        """

        changes: List[MeaningChange] = []

        if source_truth_value != target_truth_value:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.TRUTH_VALUE_CHANGE,
                    description=(
                        f"Truth value changed from {source_truth_value.value} "
                        f"to {target_truth_value.value}."
                    ),
                    severity=4.0,
                )
            )

        if source_proof_status != target_proof_status:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.PROOF_STATUS_CHANGE,
                    description=(
                        f"Proof status changed from {source_proof_status.value} "
                        f"to {target_proof_status.value}."
                    ),
                    severity=3.0,
                )
            )

        if lost_symbols:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.SYMBOL_LOSS,
                    description="Lost symbols: " + ", ".join(lost_symbols) + ".",
                    severity=min(10.0, 2.0 + len(lost_symbols) * 1.25),
                )
            )

        if lost_features:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.FEATURE_LOSS,
                    description="Lost features: " + ", ".join(lost_features) + ".",
                    severity=min(10.0, 2.5 + len(lost_features) * 1.5),
                )
            )

        if "contradiction_support" in lost_features:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.CONTRADICTION_COLLAPSE,
                    description="Contradiction-tolerant structure collapsed in the target universe.",
                    severity=8.0,
                )
            )

        if "modal_support" in lost_features:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.MODAL_COLLAPSE,
                    description="Modal structure was erased or weakened in translation.",
                    severity=7.0,
                )
            )

        if "constructive_evidence" in lost_features:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.CONSTRUCTIVE_WEAKENING,
                    description="Constructive witness/evidence requirement was weakened.",
                    severity=6.5,
                )
            )

        if "context_sensitivity" in lost_features:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.CONTEXT_ERASURE,
                    description="Context-sensitive meaning was erased or weakened.",
                    severity=6.0,
                )
            )

        if target_analysis.ambiguity_score > source_analysis.ambiguity_score + 1.5:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.AMBIGUITY_INCREASE,
                    description=(
                        f"Ambiguity increased from {source_analysis.ambiguity_score} "
                        f"to {target_analysis.ambiguity_score}."
                    ),
                    severity=target_analysis.ambiguity_score - source_analysis.ambiguity_score,
                )
            )

        if not changes:
            changes.append(
                MeaningChange(
                    kind=MeaningChangeKind.NO_CHANGE,
                    description="No major meaning change detected by the heuristic translator.",
                    severity=0.0,
                )
            )

        return changes

    @staticmethod
    def _translation_status(
        lost_symbols: List[str],
        lost_features: List[str],
        meaning_changes: List[MeaningChange],
        source_fit: float,
        target_fit: float,
    ) -> TranslationStatus:
        """
        Determines translation status.
        """

        max_severity = max(change.normalized_severity() for change in meaning_changes) if meaning_changes else 0.0

        if target_fit <= 2.0:
            return TranslationStatus.FAILED

        if lost_features and max_severity >= 7.0:
            return TranslationStatus.DISTORTED

        if lost_symbols or lost_features:
            return TranslationStatus.PARTIAL

        if target_fit < source_fit - 2.0:
            return TranslationStatus.WEAKENED

        if max_severity <= 0.5:
            return TranslationStatus.EXACT

        if max_severity <= 3.5:
            return TranslationStatus.PRESERVED

        return TranslationStatus.REQUIRES_HUMAN_REVIEW

    @staticmethod
    def _translation_confidence(
        bridge: BridgeMap,
        lost_symbols: List[str],
        lost_features: List[str],
        meaning_changes: List[MeaningChange],
        target_fit: float,
        target_ambiguity: float,
    ) -> float:
        """
        Computes translation confidence from 0 to 10.
        """

        score = 0.0
        score += bridge.bridge_strength_score() * 0.35
        score += target_fit * 0.35
        score += (10.0 - target_ambiguity) * 0.20

        average_severity = 0.0
        if meaning_changes:
            average_severity = sum(change.normalized_severity() for change in meaning_changes) / len(meaning_changes)

        score -= average_severity * 0.20
        score -= len(lost_symbols) * 0.25
        score -= len(lost_features) * 0.50

        return round(max(0.0, min(10.0, score)), 2)


if __name__ == "__main__":
    from src.bridges.bridge_map import starter_bridge_maps
    from src.toy_topoi.library import find_universe_by_name
    from src.toy_topoi.statements import starter_statements

    translator = UniverseTranslator()
    bridges = starter_bridge_maps()
    statements = starter_statements()

    for bridge in bridges:
        source_universe = find_universe_by_name(bridge.source_universe_name)
        target_universe = find_universe_by_name(bridge.target_universe_name)

        if source_universe is None or target_universe is None:
            continue

        for statement in statements:
            if statement.origin_universe == bridge.source_universe_name:
                result = translator.translate(
                    statement=statement,
                    source_universe=source_universe,
                    target_universe=target_universe,
                    bridge=bridge,
                )
                print(result.describe())
                print("-" * 80)
