import AlephOmegaMathlib.Generated.ExportedTinyMathlibSystem
import AlephOmegaMathlib.Generated.ExportedTinyMathlibMorphism
import AlephOmegaMathlib.Generated.ExportedTinyMathlibQuotient
import AlephOmegaMathlib.Generated.ExportedTinyMathlibQuotientComposition
