"""
Generated diamond diagram Mathlib exporter for Project Aleph-Omega.

This module exports the standard generated diamond diagram into the experimental
Mathlib track and includes a nontrivial quotient path equivalence proof.
"""

from dataclasses import dataclass
from pathlib import Path

from src.rigor.generated_diamond_diagram_model import build_standard_diamond_diagram


@dataclass(frozen=True)
class DiamondDiagramMathlibExportResult:
    """
    Result of exporting the generated diamond diagram to Mathlib.
    """

    output_path: Path
    import_name: str
    system_count: int
    morphism_count: int
    path_equivalence_theorem: str
    category_commutativity_theorem: str

    def describe(self) -> str:
        return (
            f"DiamondDiagramMathlibExportResult\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Systems: {self.system_count}\n"
            f"Morphisms: {self.morphism_count}\n"
            f"Path equivalence theorem: {self.path_equivalence_theorem}\n"
            f"Category theorem: {self.category_commutativity_theorem}"
        )


class DiamondDiagramMathlibExporter:
    """
    Exports the standard generated diamond diagram into AlephOmegaMathlib.
    """

    def render(self) -> str:
        """
        Renders the generated diamond diagram Mathlib Lean file.
        """

        diagram = build_standard_diamond_diagram()
        diagram.validate()

        lines = [
            "import AlephOmegaMathlib.QuotientFormalSystemCategory",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega diamond diagram Mathlib exporter.",
            "",
            "This file contains a generated finite diamond diagram and proves that",
            "the two source-to-target paths are equal as quotient morphisms by using",
            "the PreservationEquivalent relation and Quotient.sound.",
            "-/",
            "",
        ]

        for system in diagram.systems():
            model_type = f"{system.name}Model"
            sentence_type = f"{system.name}Sentence"
            system_name = f"{system.name}System"

            model0, model1 = system.models
            sentence0, sentence1 = system.sentences

            lines.extend(
                [
                    f"inductive {model_type} where",
                    f"  | {model0}",
                    f"  | {model1}",
                    "deriving DecidableEq",
                    "",
                    f"inductive {sentence_type} where",
                    f"  | {sentence0}",
                    f"  | {sentence1}",
                    "deriving DecidableEq",
                    "",
                    f"def {system_name} : FormalSystem where",
                    f"  Model := {model_type}",
                    f"  Sentence := {sentence_type}",
                    "  Sat := fun m φ =>",
                    "    match m, φ with",
                    f"    | {model_type}.{model0}, {sentence_type}.{sentence0} => True",
                    f"    | {model_type}.{model1}, {sentence_type}.{sentence1} => True",
                    "    | _, _ => False",
                    "",
                    f"def Q{system.name}System : QuotientFormalSystem where",
                    f"  system := {system_name}",
                    "",
                ]
            )

        for morphism in diagram.morphisms():
            source = morphism.source
            target = morphism.target

            source_system = f"{source.name}System"
            target_system = f"{target.name}System"
            source_model_type = f"{source.name}Model"
            source_sentence_type = f"{source.name}Sentence"
            target_model_type = f"{target.name}Model"
            target_sentence_type = f"{target.name}Sentence"

            translate_name = f"{morphism.name}Translate"
            model_map_name = f"{morphism.name}ModelMap"
            preserves_name = f"{morphism.name.lower()}_preserves"
            morphism_name = f"{morphism.name}Morphism"
            quotient_name = f"q{morphism.name}"
            category_name = f"qCategory{morphism.name}"

            lines.extend(
                [
                    f"def {translate_name} :",
                    f"  {source_system}.Sentence -> {target_system}.Sentence :=",
                    "  fun φ =>",
                    "    match φ with",
                ]
            )

            for source_sentence, target_sentence in morphism.sentence_map.items():
                lines.append(
                    f"    | {source_sentence_type}.{source_sentence} => {target_sentence_type}.{target_sentence}"
                )

            lines.extend(
                [
                    "",
                    f"def {model_map_name} :",
                    f"  {source_system}.Model -> {target_system}.Model :=",
                    "  fun m =>",
                    "    match m with",
                ]
            )

            for source_model, target_model in morphism.model_map.items():
                lines.append(
                    f"    | {source_model_type}.{source_model} => {target_model_type}.{target_model}"
                )

            lines.extend(
                [
                    "",
                    f"theorem {preserves_name} :",
                    f"  ∀ (m : {source_system}.Model) (φ : {source_system}.Sentence),",
                    f"    {source_system}.Sat m φ ->",
                    f"    {target_system}.Sat ({model_map_name} m) ({translate_name} φ) := by",
                    "      intro m φ h",
                    "      cases m <;> cases φ <;>",
                    f"        simp [{source_system}, {target_system}, {model_map_name}, {translate_name}] at h ⊢",
                    "",
                    f"def {morphism_name} :",
                    f"  PreservationMorphism {source_system} {target_system} where",
                    f"    translate := {translate_name}",
                    f"    mapModel := {model_map_name}",
                    f"    preserves := {preserves_name}",
                    "",
                    f"def {quotient_name} :",
                    f"  QuotientPreservationHom {source_system} {target_system} :=",
                    f"  quotientPreservationOf {morphism_name}",
                    "",
                    f"def {category_name} :",
                    f"  Q{source.name}System ⟶ Q{target.name}System :=",
                    f"  {quotient_name}",
                    "",
                ]
            )

        lines.extend(
            [
                "def DiamondUpperPathMorphism :",
                "  PreservationMorphism DiamondSystemASystem DiamondSystemDSystem :=",
                "  composePreservation DiamondMorphismABMorphism DiamondMorphismBDMorphism",
                "",
                "def DiamondLowerPathMorphism :",
                "  PreservationMorphism DiamondSystemASystem DiamondSystemDSystem :=",
                "  composePreservation DiamondMorphismACMorphism DiamondMorphismCDMorphism",
                "",
                "def qDiamondUpperPath :",
                "  QuotientPreservationHom DiamondSystemASystem DiamondSystemDSystem :=",
                "  quotientPreservationOf DiamondUpperPathMorphism",
                "",
                "def qDiamondLowerPath :",
                "  QuotientPreservationHom DiamondSystemASystem DiamondSystemDSystem :=",
                "  quotientPreservationOf DiamondLowerPathMorphism",
                "",
                "def qCategoryDiamondUpperPath :",
                "  QDiamondSystemASystem ⟶ QDiamondSystemDSystem :=",
                "  qDiamondUpperPath",
                "",
                "def qCategoryDiamondLowerPath :",
                "  QDiamondSystemASystem ⟶ QDiamondSystemDSystem :=",
                "  qDiamondLowerPath",
                "",
                "theorem diamond_path_translation_equivalence :",
                "  ∀ φ : DiamondSystemASystem.Sentence,",
                "    DiamondUpperPathMorphism.translate φ =",
                "    DiamondLowerPathMorphism.translate φ := by",
                "      intro φ",
                "      cases φ <;> rfl",
                "",
                "theorem diamond_path_model_map_equivalence :",
                "  ∀ m : DiamondSystemASystem.Model,",
                "    DiamondUpperPathMorphism.mapModel m =",
                "    DiamondLowerPathMorphism.mapModel m := by",
                "      intro m",
                "      cases m <;> rfl",
                "",
                "theorem diamond_paths_preservation_equivalent :",
                "  PreservationEquivalent DiamondUpperPathMorphism DiamondLowerPathMorphism := by",
                "    constructor",
                "    · exact diamond_path_translation_equivalence",
                "    · exact diamond_path_model_map_equivalence",
                "",
                "theorem q_diamond_paths_equal :",
                "  qDiamondUpperPath = qDiamondLowerPath := by",
                "    apply Quotient.sound",
                "    exact diamond_paths_preservation_equivalent",
                "",
                "theorem q_category_diamond_commutes :",
                "  qCategoryDiamondUpperPath = qCategoryDiamondLowerPath := by",
                "    exact q_diamond_paths_equal",
                "",
                "end Generated",
                "end AlephOmegaMathlib",
                "",
            ]
        )

        return "\n".join(lines)

    def export(
        self,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/DiamondDiagram.lean",
    ) -> DiamondDiagramMathlibExportResult:
        """
        Exports the diamond diagram Mathlib Lean file.
        """

        diagram = build_standard_diamond_diagram()
        diagram.validate()

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render())

        return DiamondDiagramMathlibExportResult(
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.DiamondDiagram",
            system_count=len(diagram.systems()),
            morphism_count=len(diagram.morphisms()),
            path_equivalence_theorem="q_diamond_paths_equal",
            category_commutativity_theorem="q_category_diamond_commutes",
        )


if __name__ == "__main__":
    exporter = DiamondDiagramMathlibExporter()
    result = exporter.export()

    print(result.describe())
