"""
Generated Lean artifact index for Project Aleph-Omega.

This module indexes generated Lean and generated Mathlib artifacts.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Tuple


@dataclass(frozen=True)
class GeneratedLeanArtifact:
    """
    One generated Lean artifact.
    """

    name: str
    path: str
    artifact_type: str
    generated_by: str
    verification: str
    role: str

    def describe(self) -> str:
        return (
            f"GeneratedLeanArtifact\n"
            f"Name: {self.name}\n"
            f"Path: {self.path}\n"
            f"Type: {self.artifact_type}\n"
            f"Generated by: {self.generated_by}"
        )


@dataclass(frozen=True)
class GeneratedLeanArtifactIndex:
    """
    Index of generated Lean artifacts.
    """

    title: str
    artifacts: Tuple[GeneratedLeanArtifact, ...]

    def artifact_count(self) -> int:
        return len(self.artifacts)

    def standalone_artifacts(self) -> Tuple[GeneratedLeanArtifact, ...]:
        return tuple(
            artifact
            for artifact in self.artifacts
            if "standalone" in artifact.artifact_type.lower()
        )

    def mathlib_artifacts(self) -> Tuple[GeneratedLeanArtifact, ...]:
        return tuple(
            artifact
            for artifact in self.artifacts
            if "mathlib" in artifact.artifact_type.lower()
            or "Mathlib" in artifact.verification
        )

    def quotient_artifacts(self) -> Tuple[GeneratedLeanArtifact, ...]:
        return tuple(
            artifact
            for artifact in self.artifacts
            if "quotient" in artifact.artifact_type.lower()
            or "quotient" in artifact.role.lower()
        )

    def verified_artifacts(self) -> Tuple[GeneratedLeanArtifact, ...]:
        return tuple(
            artifact
            for artifact in self.artifacts
            if "Lean" in artifact.verification
            or "Lake" in artifact.verification
            or "formal-stack" in artifact.verification
        )

    def describe(self) -> str:
        return (
            f"GeneratedLeanArtifactIndex\n"
            f"Title: {self.title}\n"
            f"Artifacts: {self.artifact_count()}\n"
            f"Standalone artifacts: {len(self.standalone_artifacts())}\n"
            f"Mathlib artifacts: {len(self.mathlib_artifacts())}\n"
            f"Quotient artifacts: {len(self.quotient_artifacts())}\n"
            f"Verified artifacts: {len(self.verified_artifacts())}"
        )


class GeneratedLeanArtifactIndexBuilder:
    """
    Builds the generated Lean artifact index.
    """

    def build(self) -> GeneratedLeanArtifactIndex:
        artifacts = (
            GeneratedLeanArtifact(
                name="ExportedTinySystem",
                path="formal/generated/ExportedTinySystem.lean",
                artifact_type="standalone finite system Lean artifact",
                generated_by="src/rigor/lean_finite_system_exporter.py",
                verification="Lean check through scripts/check_generated_lean_exports.sh",
                role="Standalone generated finite formal system with satisfaction facts.",
            ),
            GeneratedLeanArtifact(
                name="ExportedTinyMorphism",
                path="formal/generated/ExportedTinyMorphism.lean",
                artifact_type="standalone preservation morphism Lean artifact",
                generated_by="src/rigor/lean_morphism_exporter.py",
                verification="Lean check through scripts/check_generated_lean_exports.sh",
                role="Standalone generated finite satisfaction-preserving morphism.",
            ),
            GeneratedLeanArtifact(
                name="ExportedTinyMathlibSystem",
                path="formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibSystem.lean",
                artifact_type="Mathlib finite system artifact",
                generated_by="src/rigor/mathlib_finite_system_exporter.py",
                verification="Mathlib Lake build through scripts/check_generated_mathlib_exports.sh",
                role="Generated finite FormalSystem using the Mathlib-track FormalSystem definition.",
            ),
            GeneratedLeanArtifact(
                name="ExportedTinyMathlibMorphism",
                path="formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibMorphism.lean",
                artifact_type="Mathlib preservation morphism artifact",
                generated_by="src/rigor/mathlib_morphism_exporter.py",
                verification="Mathlib Lake build through scripts/check_generated_mathlib_exports.sh",
                role="Generated finite PreservationMorphism using the Mathlib-track PreservationMorphism definition.",
            ),
            GeneratedLeanArtifact(
                name="ExportedTinyMathlibQuotient",
                path="formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibQuotient.lean",
                artifact_type="Mathlib quotient wrapper artifact",
                generated_by="src/rigor/mathlib_quotient_wrapper_exporter.py",
                verification="Mathlib Lake build through scripts/check_generated_mathlib_exports.sh",
                role="Generated quotient-category wrapper for a generated preservation morphism.",
            ),
            GeneratedLeanArtifact(
                name="ExportedTinyMathlibQuotientComposition",
                path="formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibQuotientComposition.lean",
                artifact_type="Mathlib quotient composition artifact",
                generated_by="src/rigor/mathlib_quotient_composition_exporter.py",
                verification="Mathlib Lake build through scripts/check_generated_mathlib_exports.sh",
                role="Generated quotient-category composition theorem for a finite three-system chain.",
            ),
            GeneratedLeanArtifact(
                name="Generated Mathlib index",
                path="formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated.lean",
                artifact_type="Mathlib generated import index",
                generated_by="scripts/check_generated_mathlib_exports.sh",
                verification="Mathlib Lake build and formal-stack verification",
                role="Imports generated Mathlib system, morphism, quotient wrapper, and quotient composition artifacts.",
            ),
            GeneratedLeanArtifact(
                name="Standalone generated Lean checker",
                path="scripts/check_generated_lean_exports.sh",
                artifact_type="verification script",
                generated_by="manual script phase",
                verification="formal-stack verification",
                role="Regenerates and checks standalone generated Lean artifacts.",
            ),
            GeneratedLeanArtifact(
                name="Generated Mathlib checker",
                path="scripts/check_generated_mathlib_exports.sh",
                artifact_type="verification script",
                generated_by="manual script phase",
                verification="formal-stack verification",
                role="Regenerates and checks generated Mathlib artifacts including quotient artifacts.",
            ),
        )

        return GeneratedLeanArtifactIndex(
            title="Project Aleph-Omega Generated Lean Artifact Index",
            artifacts=artifacts,
        )

    def to_markdown(self, index: GeneratedLeanArtifactIndex) -> str:
        lines = [
            "# Project Aleph-Omega Generated Lean Artifact Index",
            "",
            "## Purpose",
            "",
            "This document indexes the generated Lean and generated Mathlib artifacts in Project Aleph-Omega.",
            "",
            "It is intended as a reviewer-facing map of what is generated, where it lives, how it is verified, and what role it plays.",
            "",
            "## Summary",
            "",
            f"- Artifacts indexed: {index.artifact_count()}",
            f"- Standalone artifacts: {len(index.standalone_artifacts())}",
            f"- Mathlib artifacts: {len(index.mathlib_artifacts())}",
            f"- Quotient artifacts: {len(index.quotient_artifacts())}",
            f"- Verified artifacts: {len(index.verified_artifacts())}",
            "",
            "## Artifact Table",
            "",
            "| Name | Path | Type | Generated by | Verification | Role |",
            "|---|---|---|---|---|---|",
        ]

        for artifact in index.artifacts:
            lines.append(
                f"| {artifact.name} | `{artifact.path}` | {artifact.artifact_type} | `{artifact.generated_by}` | {artifact.verification} | {artifact.role} |"
            )

        lines.extend(
            [
                "",
                "## Strongest Current Claim",
                "",
                "> Project Aleph-Omega now has a documented index of its generated Lean and generated Mathlib artifacts, including standalone finite systems, Mathlib preservation morphisms, quotient wrappers, quotient composition theorems, and verification scripts.",
                "",
                "## Boundary",
                "",
                "This index documents the current generated examples.",
                "",
                "It is not yet an automatic inventory over arbitrary generated files.",
                "",
            ]
        )

        return "\n".join(lines)

    def write_markdown(
        self,
        index: GeneratedLeanArtifactIndex,
        path: str = "docs/generated_lean_artifact_index.md",
    ) -> Path:
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.to_markdown(index))
        return output_path


if __name__ == "__main__":
    builder = GeneratedLeanArtifactIndexBuilder()
    index = builder.build()
    output_path = builder.write_markdown(index)

    print(index.describe())
    print(f"Wrote generated Lean artifact index to {output_path}")
