"""
Python-to-Lean finite system exporter for Project Aleph-Omega.

This module generates Lean code for small finite formal systems.

Phase 31B exports:

- finite model type,
- finite sentence type,
- match-defined satisfaction relation,
- positive satisfaction theorems,
- negative satisfaction theorems.

This is the first concrete bridge from Python data to Lean artifacts.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Tuple


def lean_safe_identifier(raw: str, prefix: str) -> str:
    """
    Converts an arbitrary name into a Lean-safe constructor-style identifier.
    """

    cleaned = []
    for char in raw:
        if char.isalnum():
            cleaned.append(char.lower())
        else:
            cleaned.append("_")

    name = "".join(cleaned).strip("_")

    if not name:
        name = prefix

    if name[0].isdigit():
        name = f"{prefix}_{name}"

    while "__" in name:
        name = name.replace("__", "_")

    return name


@dataclass(frozen=True)
class ExportedFiniteSystem:
    """
    Finite system data to export into Lean.
    """

    name: str
    models: Tuple[str, ...]
    sentences: Tuple[str, ...]
    satisfying_pairs: Tuple[Tuple[str, str], ...]

    def validate(self) -> None:
        """
        Validates the finite system.
        """

        if not self.name:
            raise ValueError("System name cannot be empty.")

        if not self.models:
            raise ValueError("System must contain at least one model.")

        if not self.sentences:
            raise ValueError("System must contain at least one sentence.")

        model_set = set(self.models)
        sentence_set = set(self.sentences)

        for model, sentence in self.satisfying_pairs:
            if model not in model_set:
                raise ValueError(f"Unknown model in satisfying pair: {model}")
            if sentence not in sentence_set:
                raise ValueError(f"Unknown sentence in satisfying pair: {sentence}")


@dataclass(frozen=True)
class LeanExportResult:
    """
    Result of exporting a finite system to Lean.
    """

    system_name: str
    output_path: Path
    model_count: int
    sentence_count: int
    positive_theorem_count: int
    negative_theorem_count: int

    def describe(self) -> str:
        return (
            f"LeanExportResult\n"
            f"System: {self.system_name}\n"
            f"Path: {self.output_path}\n"
            f"Models: {self.model_count}\n"
            f"Sentences: {self.sentence_count}\n"
            f"Positive theorems: {self.positive_theorem_count}\n"
            f"Negative theorems: {self.negative_theorem_count}"
        )


class LeanFiniteSystemExporter:
    """
    Exports finite system data into Lean code.
    """

    def _constructor_map(self, names: Iterable[str], prefix: str) -> dict[str, str]:
        mapping = {}
        used = set()

        for index, name in enumerate(names):
            base = lean_safe_identifier(name, prefix)
            candidate = base
            if candidate in used:
                candidate = f"{base}_{index}"

            used.add(candidate)
            mapping[name] = candidate

        return mapping

    def render(self, system: ExportedFiniteSystem) -> str:
        """
        Renders a finite system as Lean code.
        """

        system.validate()

        model_type = f"{system.name}Model"
        sentence_type = f"{system.name}Sentence"
        formal_system = f"{system.name}System"

        model_map = self._constructor_map(system.models, "m")
        sentence_map = self._constructor_map(system.sentences, "s")
        satisfying = set(system.satisfying_pairs)

        lines = [
            "namespace AlephOmegaGenerated",
            "",
            "/-",
            "Generated by Project Aleph-Omega Python-to-Lean exporter.",
            "",
            "This file contains a finite formal system generated from Python data.",
            "-/",
            "",
            "structure FormalSystem where",
            "  Model : Type",
            "  Sentence : Type",
            "  Sat : Model -> Sentence -> Prop",
            "",
            f"inductive {model_type} where",
        ]

        for model in system.models:
            lines.append(f"  | {model_map[model]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"inductive {sentence_type} where",
            ]
        )

        for sentence in system.sentences:
            lines.append(f"  | {sentence_map[sentence]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"def {formal_system} : FormalSystem where",
                f"  Model := {model_type}",
                f"  Sentence := {sentence_type}",
                "  Sat := fun m φ =>",
                "    match m, φ with",
            ]
        )

        for model, sentence in system.satisfying_pairs:
            lines.append(
                f"    | {model_type}.{model_map[model]}, {sentence_type}.{sentence_map[sentence]} => True"
            )

        lines.append("    | _, _ => False")
        lines.append("")

        positive_count = 0
        negative_count = 0

        for model in system.models:
            for sentence in system.sentences:
                theorem_suffix = f"{model_map[model]}_{sentence_map[sentence]}"
                if (model, sentence) in satisfying:
                    positive_count += 1
                    lines.extend(
                        [
                            f"theorem {system.name.lower()}_{theorem_suffix}_sat :",
                            f"  {formal_system}.Sat {model_type}.{model_map[model]} {sentence_type}.{sentence_map[sentence]} := by",
                            "    trivial",
                            "",
                        ]
                    )
                else:
                    negative_count += 1
                    lines.extend(
                        [
                            f"theorem {system.name.lower()}_{theorem_suffix}_not_sat :",
                            f"  ¬ {formal_system}.Sat {model_type}.{model_map[model]} {sentence_type}.{sentence_map[sentence]} := by",
                            "    intro h",
                            "    cases h",
                            "",
                        ]
                    )

        lines.append("end AlephOmegaGenerated")
        lines.append("")

        return "\n".join(lines)

    def export(
        self,
        system: ExportedFiniteSystem,
        path: str = "formal/generated/ExportedTinySystem.lean",
    ) -> LeanExportResult:
        """
        Exports a finite system to a Lean file.
        """

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render(system))

        total_pairs = len(system.models) * len(system.sentences)
        positive = len(system.satisfying_pairs)
        negative = total_pairs - positive

        return LeanExportResult(
            system_name=system.name,
            output_path=output_path,
            model_count=len(system.models),
            sentence_count=len(system.sentences),
            positive_theorem_count=positive,
            negative_theorem_count=negative,
        )


def tiny_export_system() -> ExportedFiniteSystem:
    """
    Standard tiny finite system used by tests and documentation.
    """

    return ExportedFiniteSystem(
        name="ExportedTiny",
        models=("m0", "m1"),
        sentences=("p", "q"),
        satisfying_pairs=(("m0", "p"), ("m1", "q")),
    )


if __name__ == "__main__":
    exporter = LeanFiniteSystemExporter()
    result = exporter.export(tiny_export_system())

    print(result.describe())
