"""
Mathlib quotient wrapper exporter for Project Aleph-Omega.

This module generates quotient-category wrapper artifacts for Python-produced
Mathlib preservation morphisms.
"""

from dataclasses import dataclass
from pathlib import Path

from src.rigor.mathlib_morphism_exporter import (
    tiny_mathlib_export_morphism,
)


@dataclass(frozen=True)
class MathlibQuotientWrapperExportResult:
    """
    Result of exporting generated quotient-category wrappers.
    """

    output_path: Path
    import_name: str
    source_object_name: str
    target_object_name: str
    quotient_morphism_name: str
    category_arrow_name: str

    def describe(self) -> str:
        return (
            f"MathlibQuotientWrapperExportResult\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Source object: {self.source_object_name}\n"
            f"Target object: {self.target_object_name}\n"
            f"Quotient morphism: {self.quotient_morphism_name}\n"
            f"Category arrow: {self.category_arrow_name}"
        )


class MathlibQuotientWrapperExporter:
    """
    Exports quotient-category wrappers for generated Mathlib morphisms.
    """

    def render(self) -> str:
        """
        Renders the generated quotient wrapper Lean file.
        """

        morphism = tiny_mathlib_export_morphism()

        source_system = f"{morphism.source.name}System"
        target_system = f"{morphism.target.name}System"
        generated_morphism = f"{morphism.name}Morphism"

        source_object = f"Q{morphism.source.name}System"
        target_object = f"Q{morphism.target.name}System"
        quotient_morphism = f"q{morphism.name}"
        category_arrow = f"qCategory{morphism.name}"

        lines = [
            "import AlephOmegaMathlib.Generated.ExportedTinyMathlibMorphism",
            "import AlephOmegaMathlib.QuotientFormalSystemCategory",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega Mathlib quotient wrapper exporter.",
            "",
            "This file wraps a generated Mathlib PreservationMorphism into the",
            "experimental quotient-category prototype.",
            "-/",
            "",
            f"def {source_object} : QuotientFormalSystem where",
            f"  system := {source_system}",
            "",
            f"def {target_object} : QuotientFormalSystem where",
            f"  system := {target_system}",
            "",
            f"def {quotient_morphism} :",
            f"  QuotientPreservationHom {source_system} {target_system} :=",
            f"  quotientPreservationOf {generated_morphism}",
            "",
            f"def {category_arrow} :",
            f"  {source_object} ⟶ {target_object} :=",
            f"  {quotient_morphism}",
            "",
            f"theorem {quotient_morphism}_is_category_arrow :",
            f"  {category_arrow} = {quotient_morphism} := by",
            "    rfl",
            "",
            "end Generated",
            "end AlephOmegaMathlib",
            "",
        ]

        return "\n".join(lines)

    def export(
        self,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibQuotient.lean",
    ) -> MathlibQuotientWrapperExportResult:
        """
        Exports the generated quotient wrapper Lean file.
        """

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render())

        return MathlibQuotientWrapperExportResult(
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.ExportedTinyMathlibQuotient",
            source_object_name="QSourceTinyMathlibSystem",
            target_object_name="QTargetTinyMathlibSystem",
            quotient_morphism_name="qTinyMathlibPreservation",
            category_arrow_name="qCategoryTinyMathlibPreservation",
        )


if __name__ == "__main__":
    exporter = MathlibQuotientWrapperExporter()
    result = exporter.export()

    print(result.describe())
