"""
Mathlib quotient composition exporter for Project Aleph-Omega.

This module generates a quotient-category composition example inside the
experimental Mathlib track.
"""

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class MathlibQuotientCompositionExportResult:
    """
    Result of exporting generated quotient-category composition artifacts.
    """

    output_path: Path
    import_name: str
    second_morphism_name: str
    composite_morphism_name: str
    composition_theorem_name: str

    def describe(self) -> str:
        return (
            f"MathlibQuotientCompositionExportResult\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Second morphism: {self.second_morphism_name}\n"
            f"Composite morphism: {self.composite_morphism_name}\n"
            f"Composition theorem: {self.composition_theorem_name}"
        )


class MathlibQuotientCompositionExporter:
    """
    Exports a generated quotient-category composition example.
    """

    def render(self) -> str:
        """
        Renders the generated quotient-composition Lean file.
        """

        lines = [
            "import AlephOmegaMathlib.Generated.ExportedTinyMathlibQuotient",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega Mathlib quotient composition exporter.",
            "",
            "This file creates a generated quotient-category composition example.",
            "-/",
            "",
            "inductive ThirdTinyMathlibModel where",
            "  | x",
            "  | y",
            "deriving DecidableEq",
            "",
            "inductive ThirdTinyMathlibSentence where",
            "  | gamma",
            "  | delta",
            "deriving DecidableEq",
            "",
            "def ThirdTinyMathlibSystem : FormalSystem where",
            "  Model := ThirdTinyMathlibModel",
            "  Sentence := ThirdTinyMathlibSentence",
            "  Sat := fun m φ =>",
            "    match m, φ with",
            "    | ThirdTinyMathlibModel.x, ThirdTinyMathlibSentence.gamma => True",
            "    | ThirdTinyMathlibModel.y, ThirdTinyMathlibSentence.delta => True",
            "    | _, _ => False",
            "",
            "def TinyMathlibSecondTranslate :",
            "  TargetTinyMathlibSystem.Sentence -> ThirdTinyMathlibSystem.Sentence :=",
            "  fun φ =>",
            "    match φ with",
            "    | TargetTinyMathlibSentence.alpha => ThirdTinyMathlibSentence.gamma",
            "    | TargetTinyMathlibSentence.beta => ThirdTinyMathlibSentence.delta",
            "",
            "def TinyMathlibSecondModelMap :",
            "  TargetTinyMathlibSystem.Model -> ThirdTinyMathlibSystem.Model :=",
            "  fun m =>",
            "    match m with",
            "    | TargetTinyMathlibModel.a => ThirdTinyMathlibModel.x",
            "    | TargetTinyMathlibModel.b => ThirdTinyMathlibModel.y",
            "",
            "theorem tinymathlibsecond_preserves :",
            "  ∀ (m : TargetTinyMathlibSystem.Model) (φ : TargetTinyMathlibSystem.Sentence),",
            "    TargetTinyMathlibSystem.Sat m φ ->",
            "    ThirdTinyMathlibSystem.Sat",
            "      (TinyMathlibSecondModelMap m)",
            "      (TinyMathlibSecondTranslate φ) := by",
            "        intro m φ h",
            "        cases m <;> cases φ <;>",
            "          simp [TargetTinyMathlibSystem, ThirdTinyMathlibSystem, TinyMathlibSecondModelMap, TinyMathlibSecondTranslate] at h ⊢",
            "",
            "def TinyMathlibSecondPreservationMorphism :",
            "  PreservationMorphism TargetTinyMathlibSystem ThirdTinyMathlibSystem where",
            "    translate := TinyMathlibSecondTranslate",
            "    mapModel := TinyMathlibSecondModelMap",
            "    preserves := tinymathlibsecond_preserves",
            "",
            "def TinyMathlibCompositePreservationMorphism :",
            "  PreservationMorphism SourceTinyMathlibSystem ThirdTinyMathlibSystem :=",
            "  composePreservation TinyMathlibPreservationMorphism TinyMathlibSecondPreservationMorphism",
            "",
            "def QThirdTinyMathlibSystem : QuotientFormalSystem where",
            "  system := ThirdTinyMathlibSystem",
            "",
            "def qTinyMathlibSecondPreservation :",
            "  QuotientPreservationHom TargetTinyMathlibSystem ThirdTinyMathlibSystem :=",
            "  quotientPreservationOf TinyMathlibSecondPreservationMorphism",
            "",
            "def qTinyMathlibCompositePreservation :",
            "  QuotientPreservationHom SourceTinyMathlibSystem ThirdTinyMathlibSystem :=",
            "  quotientComposePreservation qTinyMathlibPreservation qTinyMathlibSecondPreservation",
            "",
            "def qCategoryTinyMathlibSecondPreservation :",
            "  QTargetTinyMathlibSystem ⟶ QThirdTinyMathlibSystem :=",
            "  qTinyMathlibSecondPreservation",
            "",
            "def qCategoryTinyMathlibCompositePreservation :",
            "  QSourceTinyMathlibSystem ⟶ QThirdTinyMathlibSystem :=",
            "  qTinyMathlibCompositePreservation",
            "",
            "theorem q_category_tiny_mathlib_generated_composition :",
            "  qCategoryTinyMathlibPreservation ≫ qCategoryTinyMathlibSecondPreservation =",
            "  qCategoryTinyMathlibCompositePreservation := by",
            "    rfl",
            "",
            "end Generated",
            "end AlephOmegaMathlib",
            "",
        ]

        return "\n".join(lines)

    def export(
        self,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibQuotientComposition.lean",
    ) -> MathlibQuotientCompositionExportResult:
        """
        Exports the generated quotient-composition Lean file.
        """

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render())

        return MathlibQuotientCompositionExportResult(
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.ExportedTinyMathlibQuotientComposition",
            second_morphism_name="TinyMathlibSecondPreservationMorphism",
            composite_morphism_name="qTinyMathlibCompositePreservation",
            composition_theorem_name="q_category_tiny_mathlib_generated_composition",
        )


if __name__ == "__main__":
    exporter = MathlibQuotientCompositionExporter()
    result = exporter.export()

    print(result.describe())
