"""
Mathlib-targeted preservation morphism exporter for Project Aleph-Omega.

This module generates finite preservation morphisms inside the experimental
Mathlib project, using the existing AlephOmegaMathlib FormalSystem and
PreservationMorphism definitions.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Tuple

from src.rigor.lean_finite_system_exporter import (
    ExportedFiniteSystem,
    lean_safe_identifier,
)
from src.rigor.lean_morphism_exporter import ExportedFiniteMorphism


@dataclass(frozen=True)
class MathlibMorphismExportResult:
    """
    Result of exporting a finite preservation morphism into the Mathlib track.
    """

    morphism_name: str
    output_path: Path
    import_name: str
    source_system_name: str
    target_system_name: str

    def describe(self) -> str:
        return (
            f"MathlibMorphismExportResult\n"
            f"Morphism: {self.morphism_name}\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Source: {self.source_system_name}\n"
            f"Target: {self.target_system_name}"
        )


class MathlibMorphismExporter:
    """
    Exports finite systems and a preservation morphism into AlephOmegaMathlib.
    """

    def _constructor_map(self, names: Tuple[str, ...], prefix: str) -> Dict[str, str]:
        mapping = {}
        used = set()

        for index, name in enumerate(names):
            base = lean_safe_identifier(name, prefix)
            candidate = base

            if candidate in used:
                candidate = f"{base}_{index}"

            used.add(candidate)
            mapping[name] = candidate

        return mapping

    def render(self, morphism: ExportedFiniteMorphism) -> str:
        """
        Renders a Mathlib-targeted preservation morphism Lean file.
        """

        morphism.validate()

        source = morphism.source
        target = morphism.target

        source_model_type = f"{source.name}Model"
        source_sentence_type = f"{source.name}Sentence"
        source_system = f"{source.name}System"

        target_model_type = f"{target.name}Model"
        target_sentence_type = f"{target.name}Sentence"
        target_system = f"{target.name}System"

        source_model_map = self._constructor_map(source.models, "sm")
        source_sentence_map = self._constructor_map(source.sentences, "ss")
        target_model_map = self._constructor_map(target.models, "tm")
        target_sentence_map = self._constructor_map(target.sentences, "ts")

        translate_name = f"{morphism.name}Translate"
        model_map_name = f"{morphism.name}ModelMap"
        preserves_name = f"{morphism.name.lower()}_preserves"
        morphism_name = f"{morphism.name}Morphism"

        lines = [
            "import AlephOmegaMathlib.FormalSystemCategory",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega Mathlib-targeted morphism exporter.",
            "",
            "This file is generated inside the experimental Mathlib track and uses",
            "the existing AlephOmegaMathlib FormalSystem and PreservationMorphism definitions.",
            "-/",
            "",
            f"inductive {source_model_type} where",
        ]

        for model in source.models:
            lines.append(f"  | {source_model_map[model]}")

        lines.extend(["deriving DecidableEq", "", f"inductive {source_sentence_type} where"])

        for sentence in source.sentences:
            lines.append(f"  | {source_sentence_map[sentence]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"def {source_system} : FormalSystem where",
                f"  Model := {source_model_type}",
                f"  Sentence := {source_sentence_type}",
                "  Sat := fun m φ =>",
                "    match m, φ with",
            ]
        )

        for model, sentence in source.satisfying_pairs:
            lines.append(
                f"    | {source_model_type}.{source_model_map[model]}, {source_sentence_type}.{source_sentence_map[sentence]} => True"
            )

        lines.extend(["    | _, _ => False", "", f"inductive {target_model_type} where"])

        for model in target.models:
            lines.append(f"  | {target_model_map[model]}")

        lines.extend(["deriving DecidableEq", "", f"inductive {target_sentence_type} where"])

        for sentence in target.sentences:
            lines.append(f"  | {target_sentence_map[sentence]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"def {target_system} : FormalSystem where",
                f"  Model := {target_model_type}",
                f"  Sentence := {target_sentence_type}",
                "  Sat := fun m φ =>",
                "    match m, φ with",
            ]
        )

        for model, sentence in target.satisfying_pairs:
            lines.append(
                f"    | {target_model_type}.{target_model_map[model]}, {target_sentence_type}.{target_sentence_map[sentence]} => True"
            )

        lines.extend(
            [
                "    | _, _ => False",
                "",
                f"def {translate_name} :",
                f"  {source_system}.Sentence -> {target_system}.Sentence :=",
                "  fun φ =>",
                "    match φ with",
            ]
        )

        for source_sentence, target_sentence in morphism.sentence_map.items():
            lines.append(
                f"    | {source_sentence_type}.{source_sentence_map[source_sentence]} => {target_sentence_type}.{target_sentence_map[target_sentence]}"
            )

        lines.extend(
            [
                "",
                f"def {model_map_name} :",
                f"  {source_system}.Model -> {target_system}.Model :=",
                "  fun m =>",
                "    match m with",
            ]
        )

        for source_model, target_model in morphism.model_map.items():
            lines.append(
                f"    | {source_model_type}.{source_model_map[source_model]} => {target_model_type}.{target_model_map[target_model]}"
            )

        lines.extend(
            [
                "",
                f"theorem {preserves_name} :",
                f"  ∀ (m : {source_system}.Model) (φ : {source_system}.Sentence),",
                f"    {source_system}.Sat m φ ->",
                f"    {target_system}.Sat ({model_map_name} m) ({translate_name} φ) := by",
                "      intro m φ h",
                "      cases m <;> cases φ <;>",
                f"        simp [{source_system}, {target_system}, {model_map_name}, {translate_name}] at h ⊢",
                "",
                f"def {morphism_name} :",
                f"  PreservationMorphism {source_system} {target_system} where",
                f"    translate := {translate_name}",
                f"    mapModel := {model_map_name}",
                f"    preserves := {preserves_name}",
                "",
                "end Generated",
                "end AlephOmegaMathlib",
                "",
            ]
        )

        return "\n".join(lines)

    def export(
        self,
        morphism: ExportedFiniteMorphism,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibMorphism.lean",
    ) -> MathlibMorphismExportResult:
        """
        Exports a finite preservation morphism into the Mathlib project.
        """

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render(morphism))

        return MathlibMorphismExportResult(
            morphism_name=morphism.name,
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.ExportedTinyMathlibMorphism",
            source_system_name=morphism.source.name,
            target_system_name=morphism.target.name,
        )


def tiny_mathlib_export_morphism() -> ExportedFiniteMorphism:
    """
    Standard tiny finite preservation morphism for Mathlib-targeted export.
    """

    source = ExportedFiniteSystem(
        name="SourceTinyMathlib",
        models=("m0", "m1"),
        sentences=("p", "q"),
        satisfying_pairs=(("m0", "p"), ("m1", "q")),
    )

    target = ExportedFiniteSystem(
        name="TargetTinyMathlib",
        models=("a", "b"),
        sentences=("alpha", "beta"),
        satisfying_pairs=(("a", "alpha"), ("b", "beta")),
    )

    return ExportedFiniteMorphism(
        name="TinyMathlibPreservation",
        source=source,
        target=target,
        model_map={"m0": "a", "m1": "b"},
        sentence_map={"p": "alpha", "q": "beta"},
    )


if __name__ == "__main__":
    exporter = MathlibMorphismExporter()
    result = exporter.export(tiny_mathlib_export_morphism())

    print(result.describe())
