"""
Mathlib-targeted finite system exporter for Project Aleph-Omega.

This module generates Lean finite systems inside the experimental Mathlib
project, using the existing AlephOmegaMathlib FormalSystem definition instead
of redefining a standalone FormalSystem.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Tuple

from src.rigor.lean_finite_system_exporter import (
    ExportedFiniteSystem,
    lean_safe_identifier,
)


@dataclass(frozen=True)
class MathlibFiniteSystemExportResult:
    """
    Result of exporting a finite system into the Mathlib track.
    """

    system_name: str
    output_path: Path
    import_name: str
    model_count: int
    sentence_count: int
    positive_theorem_count: int
    negative_theorem_count: int

    def describe(self) -> str:
        return (
            f"MathlibFiniteSystemExportResult\n"
            f"System: {self.system_name}\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Models: {self.model_count}\n"
            f"Sentences: {self.sentence_count}\n"
            f"Positive theorems: {self.positive_theorem_count}\n"
            f"Negative theorems: {self.negative_theorem_count}"
        )


class MathlibFiniteSystemExporter:
    """
    Exports finite system data into the AlephOmegaMathlib project.
    """

    def _constructor_map(self, names: Iterable[str], prefix: str) -> dict[str, str]:
        mapping = {}
        used = set()

        for index, name in enumerate(names):
            base = lean_safe_identifier(name, prefix)
            candidate = base

            if candidate in used:
                candidate = f"{base}_{index}"

            used.add(candidate)
            mapping[name] = candidate

        return mapping

    def render(self, system: ExportedFiniteSystem) -> str:
        """
        Renders a finite system as Mathlib-track Lean code.
        """

        system.validate()

        model_type = f"{system.name}Model"
        sentence_type = f"{system.name}Sentence"
        formal_system = f"{system.name}System"

        model_map = self._constructor_map(system.models, "m")
        sentence_map = self._constructor_map(system.sentences, "s")
        satisfying = set(system.satisfying_pairs)

        lines = [
            "import AlephOmegaMathlib.FormalSystemCategory",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega Mathlib-targeted finite system exporter.",
            "",
            "This file is generated inside the experimental Mathlib track and uses",
            "the existing AlephOmegaMathlib FormalSystem definition.",
            "-/",
            "",
            f"inductive {model_type} where",
        ]

        for model in system.models:
            lines.append(f"  | {model_map[model]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"inductive {sentence_type} where",
            ]
        )

        for sentence in system.sentences:
            lines.append(f"  | {sentence_map[sentence]}")

        lines.extend(
            [
                "deriving DecidableEq",
                "",
                f"def {formal_system} : FormalSystem where",
                f"  Model := {model_type}",
                f"  Sentence := {sentence_type}",
                "  Sat := fun m φ =>",
                "    match m, φ with",
            ]
        )

        for model, sentence in system.satisfying_pairs:
            lines.append(
                f"    | {model_type}.{model_map[model]}, {sentence_type}.{sentence_map[sentence]} => True"
            )

        lines.append("    | _, _ => False")
        lines.append("")

        positive_count = 0
        negative_count = 0

        for model in system.models:
            for sentence in system.sentences:
                theorem_suffix = f"{model_map[model]}_{sentence_map[sentence]}"
                if (model, sentence) in satisfying:
                    positive_count += 1
                    lines.extend(
                        [
                            f"theorem {system.name.lower()}_{theorem_suffix}_sat :",
                            f"  {formal_system}.Sat {model_type}.{model_map[model]} {sentence_type}.{sentence_map[sentence]} := by",
                            "    trivial",
                            "",
                        ]
                    )
                else:
                    negative_count += 1
                    lines.extend(
                        [
                            f"theorem {system.name.lower()}_{theorem_suffix}_not_sat :",
                            f"  ¬ {formal_system}.Sat {model_type}.{model_map[model]} {sentence_type}.{sentence_map[sentence]} := by",
                            "    intro h",
                            "    cases h",
                            "",
                        ]
                    )

        lines.extend(
            [
                "end Generated",
                "end AlephOmegaMathlib",
                "",
            ]
        )

        return "\n".join(lines)

    def export(
        self,
        system: ExportedFiniteSystem,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/ExportedTinyMathlibSystem.lean",
    ) -> MathlibFiniteSystemExportResult:
        """
        Exports a finite system into the Mathlib project.
        """

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render(system))

        total_pairs = len(system.models) * len(system.sentences)
        positive = len(system.satisfying_pairs)
        negative = total_pairs - positive

        return MathlibFiniteSystemExportResult(
            system_name=system.name,
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.ExportedTinyMathlibSystem",
            model_count=len(system.models),
            sentence_count=len(system.sentences),
            positive_theorem_count=positive,
            negative_theorem_count=negative,
        )


def tiny_mathlib_export_system() -> ExportedFiniteSystem:
    """
    Standard tiny finite system for Mathlib-targeted export.
    """

    return ExportedFiniteSystem(
        name="ExportedTinyMathlib",
        models=("m0", "m1"),
        sentences=("p", "q"),
        satisfying_pairs=(("m0", "p"), ("m1", "q")),
    )


if __name__ == "__main__":
    exporter = MathlibFiniteSystemExporter()
    result = exporter.export(tiny_mathlib_export_system())

    print(result.describe())
