"""
Generated semantic lab Mathlib exporter for Project Aleph-Omega.

This module exports the standard generated semantic lab into the experimental
Mathlib track.
"""

from dataclasses import dataclass
from pathlib import Path

from src.rigor.generated_semantic_lab_model import build_standard_semantic_lab


@dataclass(frozen=True)
class SemanticLabMathlibExportResult:
    """
    Result of exporting the generated semantic lab to Mathlib.
    """

    output_path: Path
    import_name: str
    system_count: int
    morphism_count: int
    quotient_composition_count: int

    def describe(self) -> str:
        return (
            f"SemanticLabMathlibExportResult\n"
            f"Path: {self.output_path}\n"
            f"Import: {self.import_name}\n"
            f"Systems: {self.system_count}\n"
            f"Morphisms: {self.morphism_count}\n"
            f"Quotient compositions: {self.quotient_composition_count}"
        )


class SemanticLabMathlibExporter:
    """
    Exports the standard generated semantic lab into AlephOmegaMathlib.
    """

    def render(self) -> str:
        """
        Renders the generated semantic lab Mathlib Lean file.
        """

        lab = build_standard_semantic_lab()
        lab.validate()

        lines = [
            "import AlephOmegaMathlib.QuotientFormalSystemCategory",
            "",
            "namespace AlephOmegaMathlib",
            "namespace Generated",
            "",
            "/-",
            "Generated by Project Aleph-Omega semantic lab Mathlib exporter.",
            "",
            "This file contains a generated finite semantic lab with four systems,",
            "three preservation morphisms, quotient wrappers, and quotient composition",
            "theorems.",
            "-/",
            "",
        ]

        for system in lab.systems():
            model_type = f"{system.name}Model"
            sentence_type = f"{system.name}Sentence"
            system_name = f"{system.name}System"

            model0, model1 = system.models
            sentence0, sentence1 = system.sentences

            lines.extend(
                [
                    f"inductive {model_type} where",
                    f"  | {model0}",
                    f"  | {model1}",
                    "deriving DecidableEq",
                    "",
                    f"inductive {sentence_type} where",
                    f"  | {sentence0}",
                    f"  | {sentence1}",
                    "deriving DecidableEq",
                    "",
                    f"def {system_name} : FormalSystem where",
                    f"  Model := {model_type}",
                    f"  Sentence := {sentence_type}",
                    "  Sat := fun m φ =>",
                    "    match m, φ with",
                    f"    | {model_type}.{model0}, {sentence_type}.{sentence0} => True",
                    f"    | {model_type}.{model1}, {sentence_type}.{sentence1} => True",
                    "    | _, _ => False",
                    "",
                    f"def Q{system.name}System : QuotientFormalSystem where",
                    f"  system := {system_name}",
                    "",
                ]
            )

        for morphism in lab.morphisms():
            source = morphism.source
            target = morphism.target

            source_system = f"{source.name}System"
            target_system = f"{target.name}System"
            source_model_type = f"{source.name}Model"
            source_sentence_type = f"{source.name}Sentence"
            target_model_type = f"{target.name}Model"
            target_sentence_type = f"{target.name}Sentence"

            translate_name = f"{morphism.name}Translate"
            model_map_name = f"{morphism.name}ModelMap"
            preserves_name = f"{morphism.name.lower()}_preserves"
            morphism_name = f"{morphism.name}Morphism"
            quotient_name = f"q{morphism.name}"
            category_name = f"qCategory{morphism.name}"

            lines.extend(
                [
                    f"def {translate_name} :",
                    f"  {source_system}.Sentence -> {target_system}.Sentence :=",
                    "  fun φ =>",
                    "    match φ with",
                ]
            )

            for source_sentence, target_sentence in morphism.sentence_map.items():
                lines.append(
                    f"    | {source_sentence_type}.{source_sentence} => {target_sentence_type}.{target_sentence}"
                )

            lines.extend(
                [
                    "",
                    f"def {model_map_name} :",
                    f"  {source_system}.Model -> {target_system}.Model :=",
                    "  fun m =>",
                    "    match m with",
                ]
            )

            for source_model, target_model in morphism.model_map.items():
                lines.append(
                    f"    | {source_model_type}.{source_model} => {target_model_type}.{target_model}"
                )

            lines.extend(
                [
                    "",
                    f"theorem {preserves_name} :",
                    f"  ∀ (m : {source_system}.Model) (φ : {source_system}.Sentence),",
                    f"    {source_system}.Sat m φ ->",
                    f"    {target_system}.Sat ({model_map_name} m) ({translate_name} φ) := by",
                    "      intro m φ h",
                    "      cases m <;> cases φ <;>",
                    f"        simp [{source_system}, {target_system}, {model_map_name}, {translate_name}] at h ⊢",
                    "",
                    f"def {morphism_name} :",
                    f"  PreservationMorphism {source_system} {target_system} where",
                    f"    translate := {translate_name}",
                    f"    mapModel := {model_map_name}",
                    f"    preserves := {preserves_name}",
                    "",
                    f"def {quotient_name} :",
                    f"  QuotientPreservationHom {source_system} {target_system} :=",
                    f"  quotientPreservationOf {morphism_name}",
                    "",
                    f"def {category_name} :",
                    f"  Q{source.name}System ⟶ Q{target.name}System :=",
                    f"  {quotient_name}",
                    "",
                ]
            )

        lines.extend(
            [
                "def qLabCompositeAC :",
                "  QuotientPreservationHom LabSystemASystem LabSystemCSystem :=",
                "  quotientComposePreservation qLabMorphismAB qLabMorphismBC",
                "",
                "def qCategoryLabCompositeAC :",
                "  QLabSystemASystem ⟶ QLabSystemCSystem :=",
                "  qLabCompositeAC",
                "",
                "theorem q_category_lab_composition_abc :",
                "  qCategoryLabMorphismAB ≫ qCategoryLabMorphismBC =",
                "  qCategoryLabCompositeAC := by",
                "    rfl",
                "",
                "def qLabCompositeBD :",
                "  QuotientPreservationHom LabSystemBSystem LabSystemDSystem :=",
                "  quotientComposePreservation qLabMorphismBC qLabMorphismCD",
                "",
                "def qCategoryLabCompositeBD :",
                "  QLabSystemBSystem ⟶ QLabSystemDSystem :=",
                "  qLabCompositeBD",
                "",
                "theorem q_category_lab_composition_bcd :",
                "  qCategoryLabMorphismBC ≫ qCategoryLabMorphismCD =",
                "  qCategoryLabCompositeBD := by",
                "    rfl",
                "",
                "end Generated",
                "end AlephOmegaMathlib",
                "",
            ]
        )

        return "\n".join(lines)

    def export(
        self,
        path: str = "formal/aleph_omega_mathlib/AlephOmegaMathlib/Generated/SemanticLab.lean",
    ) -> SemanticLabMathlibExportResult:
        """
        Exports the semantic lab Mathlib Lean file.
        """

        lab = build_standard_semantic_lab()
        lab.validate()

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render())

        return SemanticLabMathlibExportResult(
            output_path=output_path,
            import_name="AlephOmegaMathlib.Generated.SemanticLab",
            system_count=lab.system_count(),
            morphism_count=lab.morphism_count(),
            quotient_composition_count=2,
        )


if __name__ == "__main__":
    exporter = SemanticLabMathlibExporter()
    result = exporter.export()

    print(result.describe())
