"""
Informal-to-formal translator for Project ℵω.

This module converts IntuitionObject instances into starter symbolic Statement
objects and CognitiveMorphism records.

The goal is not automatic perfect theorem formalization. The goal is to create
an inspectable pipeline from informal mathematical intuition to structured
symbolic statement.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional

from src.cognitive_morphism.intuition import IntuitionKind, IntuitionObject
from src.cognitive_morphism.morphism import (
    CognitiveMorphism,
    CognitiveMorphismKind,
    CognitiveMorphismStatus,
    CognitivePreservation,
)
from src.toy_topoi.statements import Statement, StatementKind


@dataclass(frozen=True)
class FormalizationDraft:
    """
    Draft output of converting an intuition into a symbolic statement.
    """

    intuition: IntuitionObject
    statement: Statement
    morphism: CognitiveMorphism
    symbolic_template: str
    confidence: float
    requires_review: bool
    explanation: str
    metadata: Optional[Dict[str, str]] = None

    def describe(self) -> str:
        """
        Returns a readable formalization draft report.
        """

        return (
            f"FormalizationDraft\n"
            f"Intuition: {self.intuition.name}\n"
            f"Statement: {self.statement.name}\n"
            f"Symbolic template: {self.symbolic_template}\n"
            f"Confidence: {self.confidence}\n"
            f"Requires review: {self.requires_review}\n"
            f"Explanation: {self.explanation}\n"
            f"\nGenerated statement:\n{self.statement.describe()}\n"
            f"\nGenerated morphism:\n{self.morphism.describe()}"
        )


class InformalFormalizer:
    """
    Converts informal intuition objects into starter symbolic statements.
    """

    def formalize(self, intuition: IntuitionObject) -> FormalizationDraft:
        """
        Formalizes one intuition into a starter statement and cognitive morphism.
        """

        statement_kind = self._statement_kind(intuition)
        origin_universe = self._origin_universe(intuition)
        required_symbols = self._required_symbols(intuition)
        free_variables = self._free_variables(intuition)
        symbolic_template = self._symbolic_template(intuition)

        statement = Statement(
            name=f"Formalized {intuition.name}",
            raw_text=intuition.raw_intuition,
            symbolic_form=symbolic_template,
            kind=statement_kind,
            free_variables=free_variables,
            required_symbols=required_symbols,
            origin_universe=origin_universe,
            dependencies=sorted(set(intuition.desired_properties)),
            notes=(
                f"Generated from intuition '{intuition.name}'. "
                "This is a starter symbolic formalization and requires review."
            ),
            metadata={
                "source_intuition_kind": intuition.kind.value,
                "formalization_risk": intuition.formalization_risk.value,
                "clarity_level": intuition.clarity_level.value,
            },
        )

        preservation = self._preservation(intuition, statement)
        confidence = self._confidence(intuition, preservation, statement)
        drift = self._meaning_drift(preservation)
        status = self._status(confidence, drift, preservation)

        morphism = CognitiveMorphism(
            name=f"Formalization Morphism: {intuition.name}",
            source_intuition=intuition,
            target_statement=statement,
            kind=self._morphism_kind(intuition),
            preservation=preservation,
            status=status,
            confidence=confidence,
            meaning_drift_score=drift,
            notes=(
                "Generated by InformalFormalizer. This morphism records how an "
                "informal intuition was converted into a symbolic statement."
            ),
            metadata={
                "symbolic_template": symbolic_template,
            },
        )

        requires_review = morphism.requires_review()

        explanation = self._explanation(
            intuition=intuition,
            statement=statement,
            morphism=morphism,
        )

        return FormalizationDraft(
            intuition=intuition,
            statement=statement,
            morphism=morphism,
            symbolic_template=symbolic_template,
            confidence=confidence,
            requires_review=requires_review,
            explanation=explanation,
            metadata={
                "origin_universe": origin_universe or "unknown",
                "statement_kind": statement_kind.value,
            },
        )

    def formalize_many(self, intuitions: List[IntuitionObject]) -> List[FormalizationDraft]:
        """
        Formalizes many intuitions.
        """

        return [self.formalize(intuition) for intuition in intuitions]

    @staticmethod
    def _statement_kind(intuition: IntuitionObject) -> StatementKind:
        """
        Chooses a statement kind from intuition kind.
        """

        if intuition.kind == IntuitionKind.CONTRADICTION_TOLERANCE:
            return StatementKind.CONTRADICTION

        if intuition.kind == IntuitionKind.MODAL_POSSIBILITY:
            return StatementKind.MODAL_CLAIM

        if intuition.kind == IntuitionKind.CONSTRUCTIVE_EVIDENCE:
            return StatementKind.THEOREM_CANDIDATE

        if intuition.kind == IntuitionKind.PRIME_STRUCTURE:
            return StatementKind.PRIME_GEOMETRY_CLAIM

        return StatementKind.PROPOSITION

    @staticmethod
    def _origin_universe(intuition: IntuitionObject) -> Optional[str]:
        """
        Guesses the best starter universe for the intuition.
        """

        if intuition.kind == IntuitionKind.CONTRADICTION_TOLERANCE:
            return "Paraconsistent Contradiction-Tolerant Universe"

        if intuition.kind == IntuitionKind.MODAL_POSSIBILITY:
            return "Modal Possibility Universe"

        if intuition.kind == IntuitionKind.CONSTRUCTIVE_EVIDENCE:
            return "Intuitionistic Constructive Universe"

        if intuition.kind == IntuitionKind.CATEGORY_STRUCTURAL:
            return "Many-Valued Indeterminate Universe"

        return "Generated Experimental Universe"

    @staticmethod
    def _required_symbols(intuition: IntuitionObject) -> List[str]:
        """
        Builds required symbols from candidate symbols and intuition kind.
        """

        symbols = set(symbol.lower() for symbol in intuition.candidate_symbols)

        if intuition.kind == IntuitionKind.CONTRADICTION_TOLERANCE:
            symbols.update({"both", "not", "implies"})

        if intuition.kind == IntuitionKind.MODAL_POSSIBILITY:
            symbols.update({"possible", "necessary", "not"})

        if intuition.kind == IntuitionKind.CONSTRUCTIVE_EVIDENCE:
            symbols.update({"exists", "witness", "requires"})

        if intuition.kind == IntuitionKind.CATEGORY_STRUCTURAL:
            symbols.update({"identity", "context"})

        if intuition.kind == IntuitionKind.LOGICAL_PRINCIPLE:
            symbols.update({"forall", "implies"})

        return sorted(symbols)

    @staticmethod
    def _free_variables(intuition: IntuitionObject) -> List[str]:
        """
        Extracts likely variables from candidate symbols.
        """

        variable_candidates = {"p", "q", "x", "y", "z", "c", "c1", "c2"}

        variables = [
            symbol
            for symbol in intuition.candidate_symbols
            if symbol.lower() in variable_candidates or len(symbol) == 1
        ]

        if not variables:
            variables = ["P"]

        return sorted(set(variables))

    @staticmethod
    def _symbolic_template(intuition: IntuitionObject) -> str:
        """
        Chooses a starter symbolic template.
        """

        if intuition.kind == IntuitionKind.CONTRADICTION_TOLERANCE:
            return "both(P) does_not_imply arbitrary(Q)"

        if intuition.kind == IntuitionKind.MODAL_POSSIBILITY:
            return "possible(P) and not(necessary(P))"

        if intuition.kind == IntuitionKind.CONSTRUCTIVE_EVIDENCE:
            return "exists x, P(x) requires witness(x)"

        if intuition.kind == IntuitionKind.CATEGORY_STRUCTURAL:
            return "identity(x, y, C1) and not identity(x, y, C2)"

        if intuition.kind == IntuitionKind.LOGICAL_PRINCIPLE:
            return "forall P, structure(P) implies interpretable(P)"

        return "structured_claim(P)"

    @staticmethod
    def _morphism_kind(intuition: IntuitionObject) -> CognitiveMorphismKind:
        """
        Chooses morphism kind from intuition kind.
        """

        if intuition.kind == IntuitionKind.CONTRADICTION_TOLERANCE:
            return CognitiveMorphismKind.CONTRADICTION_ENCODING

        if intuition.kind == IntuitionKind.MODAL_POSSIBILITY:
            return CognitiveMorphismKind.MODAL_ENCODING

        if intuition.kind == IntuitionKind.CONSTRUCTIVE_EVIDENCE:
            return CognitiveMorphismKind.CONSTRUCTIVE_ENCODING

        if intuition.kind == IntuitionKind.CATEGORY_STRUCTURAL:
            return CognitiveMorphismKind.CONTEXTUAL_ENCODING

        return CognitiveMorphismKind.STRUCTURAL_EXTRACTION

    @staticmethod
    def _preservation(
        intuition: IntuitionObject,
        statement: Statement,
    ) -> CognitivePreservation:
        """
        Estimates what intuition content was preserved in the statement.
        """

        statement_text = (
            statement.raw_text.lower()
            + " "
            + statement.symbolic_form.lower()
            + " "
            + " ".join(statement.required_symbols).lower()
        )

        preserved_properties = []
        lost_properties = []

        for prop in intuition.desired_properties:
            prop_words = prop.replace("_", " ").lower().split()

            if any(word in statement_text for word in prop_words):
                preserved_properties.append(prop)
            else:
                lost_properties.append(prop)

        preserved_metaphors = []
        lost_metaphors = []

        for metaphor in intuition.guiding_metaphors:
            words = metaphor.lower().split()

            if any(word in statement_text for word in words):
                preserved_metaphors.append(metaphor)
            else:
                lost_metaphors.append(metaphor)

        added_formal_properties = sorted(
            set(statement.required_symbols).difference(
                {symbol.lower() for symbol in intuition.candidate_symbols}
            )
        )

        return CognitivePreservation(
            preserved_properties=sorted(preserved_properties),
            lost_properties=sorted(lost_properties),
            added_formal_properties=added_formal_properties,
            preserved_metaphors=sorted(preserved_metaphors),
            lost_metaphors=sorted(lost_metaphors),
        )

    @staticmethod
    def _confidence(
        intuition: IntuitionObject,
        preservation: CognitivePreservation,
        statement: Statement,
    ) -> float:
        """
        Estimates formalization confidence.
        """

        score = 0.0
        score += intuition.formalization_readiness_score() * 0.40
        score += preservation.property_preservation_score() * 0.30
        score += statement.structural_complexity() * 0.20
        score += preservation.metaphor_preservation_score() * 0.10

        return round(max(0.0, min(10.0, score)), 2)

    @staticmethod
    def _meaning_drift(preservation: CognitivePreservation) -> float:
        """
        Estimates meaning drift.
        """

        score = 10.0
        score -= preservation.property_preservation_score() * 0.65
        score -= preservation.metaphor_preservation_score() * 0.20
        score += min(preservation.added_structure_count() * 0.25, 1.5)

        return round(max(0.0, min(10.0, score)), 2)

    @staticmethod
    def _status(
        confidence: float,
        drift: float,
        preservation: CognitivePreservation,
    ) -> CognitiveMorphismStatus:
        """
        Chooses cognitive morphism status.
        """

        if confidence >= 7.5 and drift <= 3.0:
            return CognitiveMorphismStatus.CLEAN

        if confidence >= 6.0 and preservation.property_preservation_score() >= 5.0:
            return CognitiveMorphismStatus.PARTIAL

        if drift >= 6.5:
            return CognitiveMorphismStatus.DRIFTED

        return CognitiveMorphismStatus.REQUIRES_HUMAN_REVIEW

    @staticmethod
    def _explanation(
        intuition: IntuitionObject,
        statement: Statement,
        morphism: CognitiveMorphism,
    ) -> str:
        """
        Builds explanation for the draft.
        """

        return (
            f"The intuition '{intuition.name}' was converted into the statement "
            f"'{statement.name}'. The formalizer selected statement kind "
            f"'{statement.kind.value}' and origin universe "
            f"'{statement.origin_universe}'. The cognitive morphism has quality "
            f"score {morphism.formalization_quality_score()} and status "
            f"'{morphism.status.value}'. This is a starter formalization and "
            f"should be reviewed before being treated as serious mathematics."
        )


if __name__ == "__main__":
    from src.cognitive_morphism.intuition import starter_intuitions

    formalizer = InformalFormalizer()

    for draft in formalizer.formalize_many(starter_intuitions()):
        print(draft.describe())
        print("-" * 100)
